### ISSUE TITLE
ImportError: attempted relative import with no known parent package when running tutorial

### ISSUE THREAD

**Issue by dlushnikov** [apahl/mol_frame#1]
I have installed Anaconda 5.0.1 (tried on Windows and Ubuntu 16.04), created virtual environment, installed dependencies as described in documentation, and added path to mol_frames to my_packages.pth according to documentation. Howeven, when running first cell of tutorial1 in Jupyter I am getting the following error:

ImportError                               Traceback (most recent call last)
<ipython-input-1-b0fb89fdcaff> in <module>()
      8 warnings.warn = warn
      9 
---> 10 from mol_frame import mol_frame as mf

~\AnacondaProjects\mol_frame-master\mol_frame\mol_frame.py in <module>()
     27 # from rdkit.Chem import Draw
     28 
---> 29 from .viewers import df_html, view
     30 from .mol_images import b64_mol
     31 x = b64_mol  # make the linter shut up

ImportError: attempted relative import with no known parent package

The same message on Ubuntu:
![import](https://user-images.githubusercontent.com/1735426/33908597-d79632ca-df80-11e7-8756-8c611c44507b.jpg)

I tried to Google for this error, however there seems to be no obvious fix. 
Please  advise how to fix this error or provide the fix by changing the code.

**Comment by apahl** [comment]
Sorry, I completely missed this issue report.

Could you try again?  
(The fix is to replace `from .viewers ...` and `from .mol_images ...` by explicit imports:  
 `from mol_frame.viewers ...` and `from mol_frame.mol_images ...` in `mol_frame.py`)
Please note that the module dependencies have changed (see the update in the README, Dask is now a requirement).  
The MolFrames now operate on Dask and Pandas DataFrames to handle arbitrarily large datasets (the tutorial was also updated).

Kind regards,
Axel

**Comment by apahl** [comment]
Closed, unless there are further comments.
